/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronDailyRadioRouteImport } from './routes/api/public/cron/daily-radio'
import { Route as ApiPublicDiscordInteractionsRouteImport } from './routes/api/public/discord/interactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyRadioRoute = ApiPublicCronDailyRadioRouteImport.update({
  id: '/api/public/cron/daily-radio',
  path: '/api/public/cron/daily-radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordInteractionsRoute =
  ApiPublicDiscordInteractionsRouteImport.update({
    id: '/api/public/discord/interactions',
    path: '/api/public/discord/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/daily-radio': typeof ApiPublicCronDailyRadioRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/daily-radio': typeof ApiPublicCronDailyRadioRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/daily-radio': typeof ApiPublicCronDailyRadioRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/public/cron/daily-radio' | '/api/public/discord/interactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cron/daily-radio' | '/api/public/discord/interactions'
  id:
    | '__root__'
    | '/'
    | '/api/public/cron/daily-radio'
    | '/api/public/discord/interactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronDailyRadioRoute: typeof ApiPublicCronDailyRadioRoute
  ApiPublicDiscordInteractionsRoute: typeof ApiPublicDiscordInteractionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-radio': {
      id: '/api/public/cron/daily-radio'
      path: '/api/public/cron/daily-radio'
      fullPath: '/api/public/cron/daily-radio'
      preLoaderRoute: typeof ApiPublicCronDailyRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/interactions': {
      id: '/api/public/discord/interactions'
      path: '/api/public/discord/interactions'
      fullPath: '/api/public/discord/interactions'
      preLoaderRoute: typeof ApiPublicDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronDailyRadioRoute: ApiPublicCronDailyRadioRoute,
  ApiPublicDiscordInteractionsRoute: ApiPublicDiscordInteractionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
